djbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import login, logout
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^questions/', include('registration.backends.default.urls')),

    # url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'', include('registr.urls')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^admin/', include(admin.site.urls)),

    # url(r'^$', TemplateView.as_view(template_name='registration/index.html'), name='index'),
    #
    # url(r'^questions/$', views.QuestionsView.as_view(), name='questions'),
    # url(r'^q<question_id>\d+/$', views.QuestionView.as_view(), name='question'),
    # url(r'^new_question/$', views.NewQuestionView.as_view(), name='new_question'),
    #
    # url(r'^accounts/', include('registration.backends.default.urls')),
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^accounts/login/$',  login),
    # url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login/'}),
)

questions/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import login, logout, views  #as auth_views
from django.views.generic import TemplateView

from questions import views as q_views

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='questions/index.html'), name='index'),
    url(r'^page(?P<page>\d+)/$', q_views.QuestionsView.as_view(),name='question_list' ),
    url(r'^(?P<question_id>\d+)/page(?P<page>\d+)/$', q_views.QuestionView.as_view(), name='question'),
    url(r'^new_comment/(?P<question_id>\d+)/$', q_views.NewQuestCommentFormView.as_view(), name='new_comment'),
    url(r'^new_question/$', q_views.NewQuestFormView.as_view(), name='new_question'),
    )

questions/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import signals
from django.core.urlresolvers import reverse

from hashlib import md5
from tasks import  new_comment_mail

from djbook.settings import DEFAULT_FROM_EMAIL


class Question(models.Model):
    author = models.ForeignKey(User)
    question_title = models.CharField(max_length=200)
    question_text = models.CharField(max_length=1500)
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __unicode__(self):
        return self.question_title + ' by ' + str(self.author)  +  ' ' +self.pub_date.strftime('%d.%m.%Y at %H:%M')

    def get_descr(self):
       return ('{} by {} {} ({}{})').format((self.question_title).encode('utf-8'), self.author.username,
                                               self.pub_date.strftime('%d.%m.%Y at %H:%M'), (self.question_text[:100]).encode('utf-8'),
                               '...' if len((self.question_text).encode('utf-8')) > 100 else '')

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - timezone.timedelta(days=1)) and self.pub_date <= timezone.now()
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def get_absolute_url(self):
        return reverse('questions:question', kwargs={'question_id': self.pk, 'page': 1})

    def avatar24(self):
        return 'http://www.gravatar.com/avatar/' + md5(self.author.email).hexdigest() + '?d=mm&s=' + str(24)

    def pretty_pub_date(self):
        return self.pub_date.strftime('%d.%m.%Y at %H:%M')


class QuestionComment(models.Model):
    question = models.ForeignKey(Question)
    author = models.ForeignKey(User)
    comment_text = models.CharField(max_length=1500)
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __unicode__(self):
        return self.comment_text[:100] + ' ' + self.pub_date.strftime('%d.%m.%Y at %H:%M')

    def avatar24(self):
        return 'http://www.gravatar.com/avatar/' + md5(self.author.email).hexdigest() + '?d=retro&s=' + str(24)

    def pretty_pub_date(self):
        return self.pub_date.strftime('%d.%m.%Y at %H:%M')


def notify_comment(sender, instance, created, **kwargs):
    '''send mail for new comment'''
    if created: # and instance.status == 1:
       subject = '%s commented your question %s' % (instance.author.username, instance.question.question_title[:50])
       message = 'User %s in your question ( %s ) add this comment: %s' % ( instance.author.username, instance.question.question_title, instance.comment_text)
       from_addr = DEFAULT_FROM_EMAIL
       recipient_list = (instance.question.author.email,)
       new_comment_mail(subject, message, from_addr, recipient_list)

signals.post_save.connect(notify_comment, sender=QuestionComment)

questions/forms.py
from django import forms

from questions.models import Question, QuestionComment



class NewQuestionForm(forms.ModelForm):
    question_title = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Question title',
                                                                   'class': 'form-control', 'required':True,
                                                                   'autofocus':True}))

    question_text = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Question text',
                                                                 'class': 'form-control', 'required':True,
                                                                 'rows': '10', 'style':'height: 138px'}))

    class Meta(object):
        model = Question
        fields = ['question_title', 'question_text', ]


class NewCommentForm(forms.ModelForm):
    comment_text = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Put your comment here',
                                                                 'class': 'form-control', 'required':True,
                                                                 'rows': '10', 'style':'height: 138px'}))

    class Meta(object):
        model = QuestionComment
        fields = ['comment_text', ]

questions/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect, request
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic

from questions.mixins import LoginRequiredMixin #, AjaxableResponseMixin
from questions.models import Question, QuestionComment
from questions.forms import NewQuestionForm, NewCommentForm


class QuestionsView(LoginRequiredMixin, generic.ListView):
    """ Class for Question list  with desc pub_date order """
    model = Question
    template_name = 'questions/questions.html'
    context_object_name = 'latest_question_list'
    paginate_by = 10

    def get_queryset(self):
         # return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date') #[:10]
         return Question.objects.order_by('-pub_date')


class QuestionView( LoginRequiredMixin, generic.ListView):  # AjaxableResponseMixin,
    """ Class for Question with comments/answers in pagination and comment form """
    model = QuestionComment
    form_class = NewCommentForm
    template_name = 'questions/question.html'
    context_object_name = 'comments_list'
    paginate_by = 10

    # def post(self, request, *args, **kwargs):
    #     comment = QuestionComment(author=self.request.user,
    #                               question=Question.objects.get(pk=kwargs['question_id']),
    #                               comment_text=self.request.POST['comment_text'])
    #     comment.save()
    #     return HttpResponseRedirect(reverse_lazy('questions:question', args=[self.kwargs['question_id'], 1]))

    def get_queryset(self):
        return QuestionComment.objects.filter(question__pk = int(self.kwargs['question_id'])).order_by('-pub_date')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(QuestionView, self).get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk = int(self.kwargs['question_id']))
        context['form'] = NewCommentForm
        return context


class NewQuestFormView(LoginRequiredMixin, generic.CreateView):
    form_class = NewQuestionForm
    template_name = 'questions/new_question.html'
    success_url = reverse_lazy('questions:question_list', args=[1]) #'/questions/page1/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class NewQuestCommentFormView(LoginRequiredMixin, generic.CreateView):
    form_class = NewCommentForm
    template_name = 'questions/question.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.question = Question.objects.get(pk=self.kwargs['question_id'])
        self.object.save()
        return HttpResponseRedirect(reverse_lazy('questions:question', args=[self.kwargs['question_id'], 1]))

questions/templates/questions/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <style type="text/css">body{padding-top:40px;padding-bottom:40px;background-color:#f5f5f5;}.form-signin{max-width:300px;padding:19px 29px 29px;margin:0 auto 20px;background-color:#fff;border:1px solid #e5e5e5;-webkit-border-radius:5px;-moz-border-radius:5px;border-radius:5px;-webkit-box-shadow:0 1px 2px rgba(0,0,0,.05);-moz-box-shadow:0 1px 2px rgba(0,0,0,.05);box-shadow:0 1px 2px rgba(0,0,0,.05);}.form-signin .form-signin-heading,.form-signin .checkbox{margin-bottom:10px;}.form-signin input[type="text"],.form-signin input[type="password"],.form-signin input[type="email"]{font-size:16px;height:auto;margin-bottom:15px;padding:7px 9px;}</style>
    <title>Questions</title>
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../static/css/bootstrap.min.css" rel="stylesheet">  -->
    {% load staticfiles %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css" />
    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->
  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/questions/">Questions</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
{#            <li class="active"><a href="#">Home</a></li>#}
            <li><a href="{% url 'questions:question_list' 1 %}">Latest</a></li>
            <li><a href="{% url 'questions:new_question' %}">New question</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="#"><i class="fa fa-user" alt="Signing from Facebook"></i> {{ user }}</a></li>
                <li><a href="{% url 'registr:auth_logout' %}">Logout</a></li>
                <li><a href="{% url 'password_reset' %}">password_reset</a></li>
            {% else %}
{#                <li><a href="/login/facebook/" class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a></li>#}
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                <li><a href="{% url 'registration_register' %}">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" >
{#     <div class="starter-template">#}
{#        <h1>Bootstrap starter template</h1>#}
{#        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>#}

{#        <div class="row padding:100px" >#}
{#            <div class="col-lg-1 col-centered">#}

                {% block content %}{% endblock %}
{#            </div>#}
{#        </div>#}
    </div><!-- /.container -->




    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>  -->

      <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '303143433227300',
          xfbml      : true,
          version    : 'v2.2'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
  </body>
</html>

questions/templates/questions/index.html
{% extends "base.html" %}
{% block content %}
{% csrf_token %}
<div class="jumbotron">
  <div class="container">
    <h1>Questions</h1>
    <p>... and some answers</p>
    <p><a class="btn btn-primary btn-lg" href="{% url 'questions:question_list' 1 %}" role="button">Learn more &raquo;</a></p>
  </div>
</div>
{% endblock %}

questions/templates/questions/new_question.html
<{% extends "base.html" %}
{% block content %}
{% csrf_token %}
<div class="container alert-info" style="padding-top: 16px;" ><h3>New Question</h3></div>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form class="form-group-lg" action="{% url 'questions:new_question' %}" method="post">
    {% csrf_token %}
    {{ form.question_title }}
    {{ form.question_text }}
    <button class="btn btn-large btn-primary btn-block" type="submit">Create question</button>
</form>

{% endblock %}

questions/templates/questions/question.html
{% extends "base.html" %}
{% block content %}
{% csrf_token %}
<div class="container alert-info" style="padding-top: 16px;" >{{ question.author  }} {{question.pretty_pub_date }}</div>
<div id="question-header">
	<h1 itemprop="name">{{ question.question_title }}</h1>
</div><hr>
<div class="container alert-dismissable">
    {{ question.question_text }}
</div><hr>


{% for comment in object_list %}
     <div class="alert-info"><img src="{{comment.avatar24}}"/> {{ comment.author.username }}<span width="100px">{{ comment.pretty_pub_date }}</span></div>
     <div class="alert">{{ comment.comment_text }}</div>
 {% empty %}
    <p>No comments yet. You may be first!</p>
{% endfor %}
{#</ul>#}
{#<a href="{% url 'questions:questions' question.id %}">Vote again?</a>#}

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
        {% if paginator.num_pages > 1 %}
            {% if page_obj.has_previous %}
                <a href="{% url 'questions:question' question.id page_obj.previous_page_number %}">&larr;</a>
            {% endif %}
            <span class="current_page">{{ page_obj.number }} / {{ paginator.num_pages }}</span>
            {% if page_obj.has_next %}
                <a href="{% url 'questions:question' question.id page_obj.next_page_number %}" >&rarr;</a>
            {% endif %}
        {% endif %}
        </span>
    </div>
{% endif %}


{#<form class="form-group-lg" action="{% url 'questions:question' question_id=question.id page=1 %}" method="post">#}
<form class="form-group-lg" action="{% url 'questions:new_comment' question_id=question.id %}" method="post">
    {% csrf_token %}
    {{ form.comment_text }}
    <button class="btn btn-large btn-primary btn-block" type="submit">Add comment</button>
</form>



{% endblock %}

questions/templates/questions/questions.html
{% extends "base.html" %}
{% block content %}
{% csrf_token %}

<div class="list-group">
{#<div class="container alert-info" style="padding-top: 16px;" ><h3> Questions</h3></div>#}

<div class="panel panel-default clearfix" style="padding-top: 24px; ">
  <div class="panel-heading">
    <h3 class="panel-title">Fresh questions</h3>
  </div>
</div>
{% for question in latest_question_list %}
     <a href="{% url 'questions:question' question.pk 1 %}" class="list-group-item"> {{ question.get_descr }}</a>
 {% empty %}
    <p>No questions</p>
{% endfor %}
</ul>
</div>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
            {% if paginator.num_pages > 1 %}
                {% if page_obj.has_previous %}
                    <a href="{% url "questions:question_list" page_obj.previous_page_number %}">&larr;</a>
                {% endif %}
                <span class="current_page">{{ page_obj.number }} / {{ paginator.num_pages }}</span>
                {% if page_obj.has_next %}
                    <a href="{% url "questions:question_list" page_obj.next_page_number %}" >&rarr;</a>
                {% endif %}
            {% endif %}
            </span>
        </div>
    {% endif %}

{% endblock %}

questions/templates/questions/stasya_test.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <table border="5">
        <thead>
            <tr bgcolor="#d3d3d3">
                <td>N</td>
                <td>1</td>
                <td>2</td>
                <td>3</td>
            </tr>
        </thead>
        <tbody>
            <tr><td>1</td><td></td><td></td><td></td></tr>
            <tr><td>2</td><td></td><td></td><td></td></tr>
            <tr><td>3</td><td></td><td></td><td></td></tr>
        </tbody>

    </table>


</body>
</html>