djbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import login, logout
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^questions/', include('registration.backends.default.urls')),

    # url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'', include('registr.urls')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^admin/', include(admin.site.urls)),

    # url(r'^$', TemplateView.as_view(template_name='registration/index.html'), name='index'),
    #
    # url(r'^questions/$', views.QuestionsView.as_view(), name='questions'),
    # url(r'^q<question_id>\d+/$', views.QuestionView.as_view(), name='question'),
    # url(r'^new_question/$', views.NewQuestionView.as_view(), name='new_question'),
    #
    # url(r'^accounts/', include('registration.backends.default.urls')),
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^accounts/login/$',  login),
    # url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login/'}),
)

questions/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import login, logout, views  #as auth_views
from django.views.generic import TemplateView

from questions import views as q_views

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='questions/index.html'), name='index'),
    url(r'^page(?P<page>\d+)/$', q_views.QuestionsView.as_view(),name='question_list' ),
    url(r'^(?P<question_id>\d+)/page(?P<page>\d+)/$', q_views.QuestionView.as_view(), name='question'),
    url(r'^new_comment/(?P<question_id>\d+)/$', q_views.NewQuestCommentFormView.as_view(), name='new_comment'),
    url(r'^new_question/$', q_views.NewQuestFormView.as_view(), name='new_question'),
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <style type="text/css">body{padding-top:40px;padding-bottom:40px;background-color:#f5f5f5;}.form-signin{max-width:300px;padding:19px 29px 29px;margin:0 auto 20px;background-color:#fff;border:1px solid #e5e5e5;-webkit-border-radius:5px;-moz-border-radius:5px;border-radius:5px;-webkit-box-shadow:0 1px 2px rgba(0,0,0,.05);-moz-box-shadow:0 1px 2px rgba(0,0,0,.05);box-shadow:0 1px 2px rgba(0,0,0,.05);}.form-signin .form-signin-heading,.form-signin .checkbox{margin-bottom:10px;}.form-signin input[type="text"],.form-signin input[type="password"],.form-signin input[type="email"]{font-size:16px;height:auto;margin-bottom:15px;padding:7px 9px;}</style>
    <title>Questions</title>
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../static/css/bootstrap.min.css" rel="stylesheet">  -->
    {% load static %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css" />
    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->
  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/questions/">Questions</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
{#            <li class="active"><a href="#">Home</a></li>#}
            <li><a href="{% url 'questions:question_list' 1 %}">Latest</a></li>
            <li><a href="{% url 'questions:new_question' %}">New question</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="#"><i class="fa fa-user" alt="Signing from Facebook"></i> {{ user }}</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                <li><a href="{% url 'password_reset' %}">password_reset</a></li>
            {% else %}
{#                <li><a href="/login/facebook/" class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a></li>#}
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                <li><a href="{% url 'registration_register' %}">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" >
{#     <div class="starter-template">#}
{#        <h1>Bootstrap starter template</h1>#}
{#        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>#}

{#        <div class="row padding:100px" >#}
{#            <div class="col-lg-1 col-centered">#}

                {% block content %}{% endblock %}
{#            </div>#}
{#        </div>#}
    </div><!-- /.container -->




    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>  -->

      <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '303143433227300',
          xfbml      : true,
          version    : 'v2.2'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
  </body>
</html>